// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repositories

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (MAccount, error)
	AddMerchantBalance(ctx context.Context, arg AddMerchantBalanceParams) (MMerchant, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (MAccount, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (MCustomer, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (MMerchant, error)
	CreateTransactionHistory(ctx context.Context, arg CreateTransactionHistoryParams) (TransactionHistory, error)
	GetAccountByCustomerID(ctx context.Context, customerID uuid.UUID) (MAccount, error)
	GetAccountByNumber(ctx context.Context, number string) (MAccount, error)
	GetAllCustomers(ctx context.Context, arg GetAllCustomersParams) ([]MCustomer, error)
	GetAllMerchants(ctx context.Context) ([]MMerchant, error)
	GetCustomerByEmail(ctx context.Context, email string) (GetCustomerByEmailRow, error)
	GetCustomerById(ctx context.Context, id uuid.UUID) (MCustomer, error)
	GetCustomerByUsername(ctx context.Context, username string) (GetCustomerByUsernameRow, error)
	GetMerchantById(ctx context.Context, id uuid.UUID) (MMerchant, error)
	GetMerchantByName(ctx context.Context, lower string) (MMerchant, error)
	GetTransactionHistory(ctx context.Context, fromAccountID uuid.UUID) ([]TransactionHistory, error)
	GetTransactionHistoryByType(ctx context.Context, arg GetTransactionHistoryByTypeParams) ([]TransactionHistory, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (MCustomer, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error
}

var _ Querier = (*Queries)(nil)
