// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: customers.sql

package db

import (
	"context"
)

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT id, id_card_type, id_card_number, first_name, last_name, phone_number, email, status, created_at, updated_at FROM m_customer
`

func (q *Queries) GetAllCustomers(ctx context.Context) ([]MCustomer, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MCustomer{}
	for rows.Next() {
		var i MCustomer
		if err := rows.Scan(
			&i.ID,
			&i.IDCardType,
			&i.IDCardNumber,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
