// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	GetAllCustomers(ctx context.Context) ([]MCustomer, error)
}

var _ Querier = (*Queries)(nil)
